<?php //[STAMP] aa740ba49ecc9060e057de5a4441b25b
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{

	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario();

}
